In [1]:
import pandas as pd
import numpy as np
import string
import datetime as dt

In [2]:
pd.__version__

'1.1.0'

# 2017-2018 NBA SEASON

In [3]:
df = pd.read_csv("2017-18/raw_scores.csv")

In [4]:
df.columns

Index(['GAME_DATE_EST', 'GAME_SEQUENCE', 'GAME_ID', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'TEAM_CITY_NAME', 'TEAM_WINS_LOSSES', 'PTS_QTR1',
       'PTS_QTR2', 'PTS_QTR3', 'PTS_QTR4', 'PTS_OT1', 'PTS_OT2', 'PTS_OT3',
       'PTS_OT4', 'PTS_OT5', 'PTS_OT6', 'PTS_OT7', 'PTS_OT8', 'PTS_OT9',
       'PTS_OT10', 'PTS', 'FG_PCT', 'FT_PCT', 'FG3_PCT', 'AST', 'REB', 'TOV'],
      dtype='object')

In [5]:
df = df.rename({"Unnamed:0": "GAME_DATE_EST"})
df.head()

GAME_DATE_EST  GAME_SEQUENCE   GAME_ID     TEAM_ID TEAM_ABBREVIATION  \
0    2017-10-17              1  21700001  1610612738               BOS   
1    2017-10-17              1  21700001  1610612739               CLE   
2    2017-10-17              2  21700002  1610612745               HOU   
3    2017-10-17              2  21700002  1610612744               GSW   
4    2017-10-18              1  21700003  1610612766               CHA   

  TEAM_CITY_NAME TEAM_WINS_LOSSES  PTS_QTR1  PTS_QTR2  PTS_QTR3  ...  PTS_OT8  \
0         Boston              0-1        19        19        33  ...        0   
1      Cleveland              1-0        29        25        18  ...        0   
2        Houston              1-0        34        28        26  ...        0   
3   Golden State              0-1        35        36        30  ...        0   
4      Charlotte              0-1        27        18        25  ...        0   

   PTS_OT9  PTS_OT10  PTS  FG_PCT  FT_PCT  FG3_PCT  AST  REB  TOV  
0        0         0   99   0.409   0.760    0.250   24   46   10  
1        0         0  102   0.458   0.840    0.227   19   50   17  
2        0         0  122   0.485   0.684    0.366   28   43   12  
3        0         0  121   0.538   0.905    0.533   34   41   17  
4        0         0   90   0.397   0.793    0.300   16   47   17  

[5 rows x 28 columns]

In [6]:
df.PTS_OT4.unique()

array([0], dtype=int64)

In [7]:
df.PTS_OT5.unique()

array([0], dtype=int64)

In [8]:
df.PTS_OT6.unique()

array([0], dtype=int64)

In [9]:
df.PTS_OT7.unique()

array([0], dtype=int64)

In [10]:
df.PTS_OT8.unique()

array([0], dtype=int64)

In [11]:
df.PTS_OT9.unique()

array([0], dtype=int64)

In [12]:
df = df.drop(["PTS_OT4", "PTS_OT5", "PTS_OT6", "PTS_OT7", "PTS_OT8", "PTS_OT9"], axis=1)
df.head()

GAME_DATE_EST  GAME_SEQUENCE   GAME_ID     TEAM_ID TEAM_ABBREVIATION  \
0    2017-10-17              1  21700001  1610612738               BOS   
1    2017-10-17              1  21700001  1610612739               CLE   
2    2017-10-17              2  21700002  1610612745               HOU   
3    2017-10-17              2  21700002  1610612744               GSW   
4    2017-10-18              1  21700003  1610612766               CHA   

  TEAM_CITY_NAME TEAM_WINS_LOSSES  PTS_QTR1  PTS_QTR2  PTS_QTR3  ...  PTS_OT2  \
0         Boston              0-1        19        19        33  ...        0   
1      Cleveland              1-0        29        25        18  ...        0   
2        Houston              1-0        34        28        26  ...        0   
3   Golden State              0-1        35        36        30  ...        0   
4      Charlotte              0-1        27        18        25  ...        0   

   PTS_OT3  PTS_OT10  PTS  FG_PCT  FT_PCT  FG3_PCT  AST  REB  TOV  
0        0         0   99   0.409   0.760    0.250   24   46   10  
1        0         0  102   0.458   0.840    0.227   19   50   17  
2        0         0  122   0.485   0.684    0.366   28   43   12  
3        0         0  121   0.538   0.905    0.533   34   41   17  
4        0         0   90   0.397   0.793    0.300   16   47   17  

[5 rows x 22 columns]

In [13]:
df = df.drop(["PTS_OT10"], axis=1)

In [14]:
df.columns

Index(['GAME_DATE_EST', 'GAME_SEQUENCE', 'GAME_ID', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'TEAM_CITY_NAME', 'TEAM_WINS_LOSSES', 'PTS_QTR1',
       'PTS_QTR2', 'PTS_QTR3', 'PTS_QTR4', 'PTS_OT1', 'PTS_OT2', 'PTS_OT3',
       'PTS', 'FG_PCT', 'FT_PCT', 'FG3_PCT', 'AST', 'REB', 'TOV'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2462 entries, 0 to 2461
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   GAME_DATE_EST      2462 non-null   object 
 1   GAME_SEQUENCE      2462 non-null   int64  
 2   GAME_ID            2462 non-null   int64  
 3   TEAM_ID            2462 non-null   int64  
 4   TEAM_ABBREVIATION  2462 non-null   object 
 5   TEAM_CITY_NAME     2462 non-null   object 
 6   TEAM_WINS_LOSSES   2462 non-null   object 
 7   PTS_QTR1           2462 non-null   int64  
 8   PTS_QTR2           2462 non-null   int64  
 9   PTS_QTR3           2462 non-null   int64  
 10  PTS_QTR4           2462 non-null   int64  
 11  PTS_OT1            2462 non-null   int64  
 12  PTS_OT2            2462 non-null   int64  
 13  PTS_OT3            2462 non-null   int64  
 14  PTS                2462 non-null   int64  
 15  FG_PCT             2462 non-null   float64
 16  FT_PCT             2462 

In [16]:
df.head()

GAME_DATE_EST  GAME_SEQUENCE   GAME_ID     TEAM_ID TEAM_ABBREVIATION  \
0    2017-10-17              1  21700001  1610612738               BOS   
1    2017-10-17              1  21700001  1610612739               CLE   
2    2017-10-17              2  21700002  1610612745               HOU   
3    2017-10-17              2  21700002  1610612744               GSW   
4    2017-10-18              1  21700003  1610612766               CHA   

  TEAM_CITY_NAME TEAM_WINS_LOSSES  PTS_QTR1  PTS_QTR2  PTS_QTR3  ...  PTS_OT1  \
0         Boston              0-1        19        19        33  ...        0   
1      Cleveland              1-0        29        25        18  ...        0   
2        Houston              1-0        34        28        26  ...        0   
3   Golden State              0-1        35        36        30  ...        0   
4      Charlotte              0-1        27        18        25  ...        0   

   PTS_OT2  PTS_OT3  PTS  FG_PCT  FT_PCT  FG3_PCT  AST  REB  TOV  
0        0        0   99   0.409   0.760    0.250   24   46   10  
1        0        0  102   0.458   0.840    0.227   19   50   17  
2        0        0  122   0.485   0.684    0.366   28   43   12  
3        0        0  121   0.538   0.905    0.533   34   41   17  
4        0        0   90   0.397   0.793    0.300   16   47   17  

[5 rows x 21 columns]

In [17]:
vegas_df = pd.read_csv("2017-18/vegas.csv", parse_dates=[0])

In [18]:
vegas_df

Date Location           Team       OppTeam      TeamId    GameId  \
0    2017-10-17     away         Boston     Cleveland  1610612738  21700001   
1    2017-10-17     home      Cleveland        Boston  1610612739  21700001   
2    2017-10-17     away        Houston  Golden State  1610612745  21700002   
3    2017-10-17     home   Golden State       Houston  1610612744  21700002   
4    2017-10-18     away      Charlotte       Detroit  1610612766  21700003   
...         ...      ...            ...           ...         ...       ...   
2455 2018-04-11     home  L.A. Clippers   L.A. Lakers  1610612746  21701228   
2456 2018-04-11     away           Utah      Portland  1610612762  21701229   
2457 2018-04-11     home       Portland          Utah  1610612757  21701229   
2458 2018-04-11     away        Houston    Sacramento  1610612745  21701230   
2459 2018-04-11     home     Sacramento       Houston  1610612758  21701230   

      PercentBet_ML  Open_Line_ML  Pinnacle_ML  5dimes_ML  ...  \
0              50.4         150.0          166        170  ...   
1              49.6        -170.0         -185       -185  ...   
2              52.7         405.0          377        420  ...   
3              47.3        -500.0         -440       -475  ...   
4              51.3         130.0          127        130  ...   
...             ...           ...          ...        ...  ...   
2455           52.2        -145.0         -130       -133  ...   
2456           58.2         140.0          118        115  ...   
2457           41.8        -160.0         -130       -125  ...   
2458           46.9        -155.0          118        123  ...   
2459           53.1         135.0         -130       -133  ...   

      Average_Line_OU  Average_Odds_OU  Best_Line_OU  Worst_Line_OU  \
0              216.17          -106.83         216.5          216.0   
1              216.17          -108.17         216.5          216.0   
2              231.75          -109.67         235.0          230.5   
3              231.75          -105.33         235.0          230.5   
4              202.17          -107.83         203.0          202.0   
...               ...              ...           ...            ...   
2455           215.08          -108.00         217.0          214.5   
2456           202.42          -109.33         203.0          202.0   
2457           202.42          -107.50         203.0          202.0   
2458           201.67          -107.50         204.5          201.0   
2459           201.67          -107.50         204.5          201.0   

      Best_Odds_OU  Worst_Odds_OU    Pts  Spread  Result  Total  
0           -101.0           -110   99.0    -3.0       L  201.0  
1           -105.0           -110  102.0     3.0       W  201.0  
2           -103.0           -115  122.0     1.0       W  243.0  
3           -100.0           -110  121.0    -1.0       L  243.0  
4           -102.0           -115   90.0   -12.0       L  192.0  
...            ...            ...    ...     ...     ...    ...  
2455        -103.0           -115  100.0   -15.0       L  215.0  
2456        -105.0           -116   93.0    -9.0       L  195.0  
2457        -105.0           -110  102.0     9.0       W  195.0  
2458        -105.0           -110   83.0   -13.0       L  179.0  
2459        -100.0           -115   96.0    13.0       W  179.0  

[2460 rows x 58 columns]

In [19]:
merged_df = vegas_df.merge(df, left_on=["GameId", "TeamId"], right_on=["GAME_ID", "TEAM_ID"])

In [20]:
merged_df.columns

Index(['Date', 'Location', 'Team', 'OppTeam', 'TeamId', 'GameId',
       'PercentBet_ML', 'Open_Line_ML', 'Pinnacle_ML', '5dimes_ML',
       'Heritage_ML', 'Bovada_ML', 'Betonline_ML', 'Average_Line_ML',
       'Best_Line_ML', 'Worst_Line_ML', 'PercentBet_Spread',
       'Open_Line_Spread', 'Open_Odds_Spread', 'Pinnacle_Line_Spread',
       'Pinnacle_Odds_Spread', '5dimes_Line_Spread', '5dimes_Odds_Spread',
       'Heritage_Line_Spread', 'Heritage_Odds_Spread', 'Bovada_Line_Spread',
       'Bovada_Odds_Spread', 'Betonline_Line_Spread', 'Betonline_Odds_Spread',
       'Average_Line_Spread', 'Average_Odds_Spread', 'Best_Line_Spread',
       'Worst_Line_Spread', 'Best_Odds_Spread', 'Worst_Odds_Spread',
       'PercentBet_OU', 'Open_Line_OU', 'Open_Odds_OU', 'Pinnacle_Line_OU',
       'Pinnacle_Odds_OU', '5dimes_Line_OU', '5dimes_Odds_OU',
       'Heritage_Line_OU', 'Heritage_Odds_OU', 'Bovada_Line_OU',
       'Bovada_Odds_OU', 'Betonline_Line_OU', 'Betonline_Odds_OU',
       'Average_Line

In [21]:
merged_df.loc[:, ["Team", "TEAM_ABBREVIATION"]]

Team TEAM_ABBREVIATION
0            Boston               BOS
1         Cleveland               CLE
2           Houston               HOU
3      Golden State               GSW
4         Charlotte               CHA
...             ...               ...
2455  L.A. Clippers               LAC
2456           Utah               UTA
2457       Portland               POR
2458        Houston               HOU
2459     Sacramento               SAC

[2460 rows x 2 columns]

In [22]:
dict(merged_df.dtypes)

{'Date': dtype('<M8[ns]'),
 'Location': dtype('O'),
 'Team': dtype('O'),
 'OppTeam': dtype('O'),
 'TeamId': dtype('int64'),
 'GameId': dtype('int64'),
 'PercentBet_ML': dtype('float64'),
 'Open_Line_ML': dtype('float64'),
 'Pinnacle_ML': dtype('int64'),
 '5dimes_ML': dtype('int64'),
 'Heritage_ML': dtype('float64'),
 'Bovada_ML': dtype('float64'),
 'Betonline_ML': dtype('float64'),
 'Average_Line_ML': dtype('float64'),
 'Best_Line_ML': dtype('float64'),
 'Worst_Line_ML': dtype('float64'),
 'PercentBet_Spread': dtype('float64'),
 'Open_Line_Spread': dtype('float64'),
 'Open_Odds_Spread': dtype('int64'),
 'Pinnacle_Line_Spread': dtype('float64'),
 'Pinnacle_Odds_Spread': dtype('int64'),
 '5dimes_Line_Spread': dtype('float64'),
 '5dimes_Odds_Spread': dtype('int64'),
 'Heritage_Line_Spread': dtype('float64'),
 'Heritage_Odds_Spread': dtype('int64'),
 'Bovada_Line_Spread': dtype('float64'),
 'Bovada_Odds_Spread': dtype('int64'),
 'Betonline_Line_Spread': dtype('float64'),
 'Betonline_Odds_S

In [30]:
merged_df.loc[:,[f for f in dict(merged_df.dtypes).keys() if str(f).startswith("Betonline")] + ["Date","Total", "TEAM_ABBREVIATION", "Result", "PTS"]]

Betonline_ML  Betonline_Line_Spread  Betonline_Odds_Spread  \
0            175.0                    4.5                   -109   
1           -205.0                   -4.5                   -111   
2            375.0                    9.5                   -103   
3           -450.0                   -9.5                   -117   
4            123.0                    2.5                   -113   
...            ...                    ...                    ...   
2455        -135.0                   -2.5                   -110   
2456         113.0                    2.0                   -105   
2457        -133.0                   -2.0                   -115   
2458         120.0                    2.5                   -103   
2459        -140.0                   -2.5                   -117   

      Betonline_Line_OU  Betonline_Odds_OU       Date  Total  \
0                 216.0               -110 2017-10-17  201.0   
1                 216.0               -110 2017-10-17  201.0   
2                 230.5               -115 2017-10-17  243.0   
3                 230.5               -105 2017-10-17  243.0   
4                 202.0               -115 2017-10-18  192.0   
...                 ...                ...        ...    ...   
2455              214.5               -111 2018-04-11  215.0   
2456              202.5               -110 2018-04-11  195.0   
2457              202.5               -110 2018-04-11  195.0   
2458              201.0               -110 2018-04-11  179.0   
2459              201.0               -110 2018-04-11  179.0   

     TEAM_ABBREVIATION Result  PTS  
0                  BOS      L   99  
1                  CLE      W  102  
2                  HOU      W  122  
3                  GSW      L  121  
4                  CHA      L   90  
...                ...    ...  ...  
2455               LAC      L  100  
2456               UTA      L   93  
2457               POR      W  102  
2458               HOU      L   83  
2459               SAC      W   96  

[2460 rows x 10 columns]