In [1]:
import pandas as pd
import numpy as np
import string
import datetime as dt
import math

In [2]:
pd.__version__

'1.1.0'

# 2017-2018 NBA SEASON

In [3]:
df = pd.read_csv("2017-18/raw_scores.csv")

In [4]:
df.columns

Index(['GAME_DATE_EST', 'GAME_SEQUENCE', 'GAME_ID', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'TEAM_CITY_NAME', 'TEAM_WINS_LOSSES', 'PTS_QTR1',
       'PTS_QTR2', 'PTS_QTR3', 'PTS_QTR4', 'PTS_OT1', 'PTS_OT2', 'PTS_OT3',
       'PTS_OT4', 'PTS_OT5', 'PTS_OT6', 'PTS_OT7', 'PTS_OT8', 'PTS_OT9',
       'PTS_OT10', 'PTS', 'FG_PCT', 'FT_PCT', 'FG3_PCT', 'AST', 'REB', 'TOV'],
      dtype='object')

In [7]:
df.PTS_OT4.unique()

array([0], dtype=int64)

In [8]:
df.PTS_OT5.unique()

array([0], dtype=int64)

In [9]:
df.PTS_OT6.unique()

array([0], dtype=int64)

In [10]:
df.PTS_OT7.unique()

array([0], dtype=int64)

In [11]:
df.PTS_OT8.unique()

array([0], dtype=int64)

In [12]:
df.PTS_OT9.unique()

array([0], dtype=int64)

In [6]:
df = df.drop(["PTS_OT4", "PTS_OT5", "PTS_OT6", "PTS_OT7", "PTS_OT8", "PTS_OT9"], axis=1)
df.head()

GAME_DATE_EST  GAME_SEQUENCE   GAME_ID     TEAM_ID TEAM_ABBREVIATION  \
0    2017-10-17              1  21700001  1610612738               BOS   
1    2017-10-17              1  21700001  1610612739               CLE   
2    2017-10-17              2  21700002  1610612745               HOU   
3    2017-10-17              2  21700002  1610612744               GSW   
4    2017-10-18              1  21700003  1610612766               CHA   

  TEAM_CITY_NAME TEAM_WINS_LOSSES  PTS_QTR1  PTS_QTR2  PTS_QTR3  ...  PTS_OT2  \
0         Boston              0-1        19        19        33  ...        0   
1      Cleveland              1-0        29        25        18  ...        0   
2        Houston              1-0        34        28        26  ...        0   
3   Golden State              0-1        35        36        30  ...        0   
4      Charlotte              0-1        27        18        25  ...        0   

   PTS_OT3  PTS_OT10  PTS  FG_PCT  FT_PCT  FG3_PCT  AST  REB  TOV  
0        0         0   99   0.409   0.760    0.250   24   46   10  
1        0         0  102   0.458   0.840    0.227   19   50   17  
2        0         0  122   0.485   0.684    0.366   28   43   12  
3        0         0  121   0.538   0.905    0.533   34   41   17  
4        0         0   90   0.397   0.793    0.300   16   47   17  

[5 rows x 22 columns]

In [7]:
df = df.drop(["PTS_OT10"], axis=1)

In [8]:
df.columns

Index(['GAME_DATE_EST', 'GAME_SEQUENCE', 'GAME_ID', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'TEAM_CITY_NAME', 'TEAM_WINS_LOSSES', 'PTS_QTR1',
       'PTS_QTR2', 'PTS_QTR3', 'PTS_QTR4', 'PTS_OT1', 'PTS_OT2', 'PTS_OT3',
       'PTS', 'FG_PCT', 'FT_PCT', 'FG3_PCT', 'AST', 'REB', 'TOV'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2462 entries, 0 to 2461
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   GAME_DATE_EST      2462 non-null   object 
 1   GAME_SEQUENCE      2462 non-null   int64  
 2   GAME_ID            2462 non-null   int64  
 3   TEAM_ID            2462 non-null   int64  
 4   TEAM_ABBREVIATION  2462 non-null   object 
 5   TEAM_CITY_NAME     2462 non-null   object 
 6   TEAM_WINS_LOSSES   2462 non-null   object 
 7   PTS_QTR1           2462 non-null   int64  
 8   PTS_QTR2           2462 non-null   int64  
 9   PTS_QTR3           2462 non-null   int64  
 10  PTS_QTR4           2462 non-null   int64  
 11  PTS_OT1            2462 non-null   int64  
 12  PTS_OT2            2462 non-null   int64  
 13  PTS_OT3            2462 non-null   int64  
 14  PTS                2462 non-null   int64  
 15  FG_PCT             2462 non-null   float64
 16  FT_PCT             2462 

In [10]:
df.head()

GAME_DATE_EST  GAME_SEQUENCE   GAME_ID     TEAM_ID TEAM_ABBREVIATION  \
0    2017-10-17              1  21700001  1610612738               BOS   
1    2017-10-17              1  21700001  1610612739               CLE   
2    2017-10-17              2  21700002  1610612745               HOU   
3    2017-10-17              2  21700002  1610612744               GSW   
4    2017-10-18              1  21700003  1610612766               CHA   

  TEAM_CITY_NAME TEAM_WINS_LOSSES  PTS_QTR1  PTS_QTR2  PTS_QTR3  ...  PTS_OT1  \
0         Boston              0-1        19        19        33  ...        0   
1      Cleveland              1-0        29        25        18  ...        0   
2        Houston              1-0        34        28        26  ...        0   
3   Golden State              0-1        35        36        30  ...        0   
4      Charlotte              0-1        27        18        25  ...        0   

   PTS_OT2  PTS_OT3  PTS  FG_PCT  FT_PCT  FG3_PCT  AST  REB  TOV  
0        0        0   99   0.409   0.760    0.250   24   46   10  
1        0        0  102   0.458   0.840    0.227   19   50   17  
2        0        0  122   0.485   0.684    0.366   28   43   12  
3        0        0  121   0.538   0.905    0.533   34   41   17  
4        0        0   90   0.397   0.793    0.300   16   47   17  

[5 rows x 21 columns]

In [11]:
vegas_df = pd.read_csv("2017-18/vegas.csv", parse_dates=[0])

In [12]:
vegas_df

Date Location           Team       OppTeam      TeamId    GameId  \
0    2017-10-17     away         Boston     Cleveland  1610612738  21700001   
1    2017-10-17     home      Cleveland        Boston  1610612739  21700001   
2    2017-10-17     away        Houston  Golden State  1610612745  21700002   
3    2017-10-17     home   Golden State       Houston  1610612744  21700002   
4    2017-10-18     away      Charlotte       Detroit  1610612766  21700003   
...         ...      ...            ...           ...         ...       ...   
2455 2018-04-11     home  L.A. Clippers   L.A. Lakers  1610612746  21701228   
2456 2018-04-11     away           Utah      Portland  1610612762  21701229   
2457 2018-04-11     home       Portland          Utah  1610612757  21701229   
2458 2018-04-11     away        Houston    Sacramento  1610612745  21701230   
2459 2018-04-11     home     Sacramento       Houston  1610612758  21701230   

      PercentBet_ML  Open_Line_ML  Pinnacle_ML  5dimes_ML  ...  \
0              50.4         150.0          166        170  ...   
1              49.6        -170.0         -185       -185  ...   
2              52.7         405.0          377        420  ...   
3              47.3        -500.0         -440       -475  ...   
4              51.3         130.0          127        130  ...   
...             ...           ...          ...        ...  ...   
2455           52.2        -145.0         -130       -133  ...   
2456           58.2         140.0          118        115  ...   
2457           41.8        -160.0         -130       -125  ...   
2458           46.9        -155.0          118        123  ...   
2459           53.1         135.0         -130       -133  ...   

      Average_Line_OU  Average_Odds_OU  Best_Line_OU  Worst_Line_OU  \
0              216.17          -106.83         216.5          216.0   
1              216.17          -108.17         216.5          216.0   
2              231.75          -109.67         235.0          230.5   
3              231.75          -105.33         235.0          230.5   
4              202.17          -107.83         203.0          202.0   
...               ...              ...           ...            ...   
2455           215.08          -108.00         217.0          214.5   
2456           202.42          -109.33         203.0          202.0   
2457           202.42          -107.50         203.0          202.0   
2458           201.67          -107.50         204.5          201.0   
2459           201.67          -107.50         204.5          201.0   

      Best_Odds_OU  Worst_Odds_OU    Pts  Spread  Result  Total  
0           -101.0           -110   99.0    -3.0       L  201.0  
1           -105.0           -110  102.0     3.0       W  201.0  
2           -103.0           -115  122.0     1.0       W  243.0  
3           -100.0           -110  121.0    -1.0       L  243.0  
4           -102.0           -115   90.0   -12.0       L  192.0  
...            ...            ...    ...     ...     ...    ...  
2455        -103.0           -115  100.0   -15.0       L  215.0  
2456        -105.0           -116   93.0    -9.0       L  195.0  
2457        -105.0           -110  102.0     9.0       W  195.0  
2458        -105.0           -110   83.0   -13.0       L  179.0  
2459        -100.0           -115   96.0    13.0       W  179.0  

[2460 rows x 58 columns]

In [13]:
merged_df = vegas_df.merge(df, left_on=["GameId", "TeamId"], right_on=["GAME_ID", "TEAM_ID"])

In [14]:
merged_df.columns

Index(['Date', 'Location', 'Team', 'OppTeam', 'TeamId', 'GameId',
       'PercentBet_ML', 'Open_Line_ML', 'Pinnacle_ML', '5dimes_ML',
       'Heritage_ML', 'Bovada_ML', 'Betonline_ML', 'Average_Line_ML',
       'Best_Line_ML', 'Worst_Line_ML', 'PercentBet_Spread',
       'Open_Line_Spread', 'Open_Odds_Spread', 'Pinnacle_Line_Spread',
       'Pinnacle_Odds_Spread', '5dimes_Line_Spread', '5dimes_Odds_Spread',
       'Heritage_Line_Spread', 'Heritage_Odds_Spread', 'Bovada_Line_Spread',
       'Bovada_Odds_Spread', 'Betonline_Line_Spread', 'Betonline_Odds_Spread',
       'Average_Line_Spread', 'Average_Odds_Spread', 'Best_Line_Spread',
       'Worst_Line_Spread', 'Best_Odds_Spread', 'Worst_Odds_Spread',
       'PercentBet_OU', 'Open_Line_OU', 'Open_Odds_OU', 'Pinnacle_Line_OU',
       'Pinnacle_Odds_OU', '5dimes_Line_OU', '5dimes_Odds_OU',
       'Heritage_Line_OU', 'Heritage_Odds_OU', 'Bovada_Line_OU',
       'Bovada_Odds_OU', 'Betonline_Line_OU', 'Betonline_Odds_OU',
       'Average_Line

In [15]:
merged_df.groupby('Team').mean()

TeamId        GameId  PercentBet_ML  Open_Line_ML  \
Team                                                                     
Atlanta        1.610613e+09  2.170061e+07      47.162195    247.524390   
Boston         1.610613e+09  2.170060e+07      56.830488   -162.073171   
Brooklyn       1.610613e+09  2.170061e+07      47.236585    190.333333   
Charlotte      1.610613e+09  2.170062e+07      43.520732    -32.987805   
Chicago        1.610613e+09  2.170062e+07      50.650000    243.487805   
Cleveland      1.610613e+09  2.170062e+07      56.537805   -293.914634   
Dallas         1.610613e+09  2.170061e+07      45.351220    166.629630   
Denver         1.610613e+09  2.170062e+07      45.173171    -94.000000   
Detroit        1.610613e+09  2.170062e+07      48.780488    -20.475610   
Golden State   1.610613e+09  2.170061e+07      49.039024   -535.189873   
Houston        1.610613e+09  2.170062e+07      51.532927   -518.804878   
Indiana        1.610613e+09  2.170060e+07      50.865854     -6.987805   
L.A. Clippers  1.610613e+09  2.170063e+07      48.798780     -2.073171   
L.A. Lakers    1.610613e+09  2.170063e+07      53.235366    144.890244   
Memphis        1.610613e+09  2.170062e+07      46.215854    206.530864   
Miami          1.610613e+09  2.170062e+07      47.501220    -59.414634   
Milwaukee      1.610613e+09  2.170063e+07      51.786585    -83.902439   
Minnesota      1.610613e+09  2.170060e+07      51.212195   -194.048780   
New Orleans    1.610613e+09  2.170062e+07      49.175610    -63.536585   
New York       1.610613e+09  2.170061e+07      50.803659    195.682927   
Oklahoma City  1.610613e+09  2.170061e+07      55.209756   -256.365854   
Orlando        1.610613e+09  2.170061e+07      50.270732    182.695122   
Philadelphia   1.610613e+09  2.170063e+07      48.778049   -120.975309   
Phoenix        1.610613e+09  2.170060e+07      49.524390    334.137500   
Portland       1.610613e+09  2.170062e+07      53.963415    -85.259259   
Sacramento     1.610613e+09  2.170062e+07      50.342683    277.426829   
San Antonio    1.610613e+09  2.170061e+07      52.496341   -175.731707   
Toronto        1.610613e+09  2.170063e+07      51.528049   -288.317073   
Utah           1.610613e+09  2.170061e+07      48.389024   -148.121951   
Washington     1.610613e+09  2.170061e+07      48.087805   -135.121951   

               Pinnacle_ML   5dimes_ML  Heritage_ML   Bovada_ML  Betonline_ML  \
Team                                                                            
Atlanta         253.548780  266.621951   253.375000  232.073171    247.829268   
Boston         -126.390244 -129.024390  -136.358025 -156.158537   -140.219512   
Brooklyn        207.609756  201.524390   199.512195  165.061728    182.333333   
Charlotte       -57.170732  -72.707317   -63.292683  -58.719512    -61.085366   
Chicago         259.658537  246.170732   251.125000  239.938272    251.292683   
Cleveland      -273.390244 -232.560976  -291.585366 -331.463415   -288.268293   
Dallas          171.524390  192.256098   175.426829  164.085366    159.777778   
Denver         -106.341463  -86.951220  -122.682927 -117.621951   -113.280488   
Detroit         -19.658537   -7.573171   -30.426829  -37.134146    -19.695122   
Golden State   -545.853659 -565.914634  -596.666667 -636.219512   -545.493671   
Houston        -545.951220 -536.292683  -562.743902 -504.687500   -541.500000   
Indiana           0.914634   16.219512    -7.439024  -11.951220     -5.195122   
L.A. Clippers     0.743902  -34.243902    -3.231707  -15.548780     -0.658537   
L.A. Lakers     146.243902  154.329268   148.475610  129.756098    140.878049   
Memphis         236.548780  226.439024   228.475610  197.469136    221.925926   
Miami           -51.024390  -49.634146   -62.682927  -71.049383    -64.207317   
Milwaukee       -90.292683  -75.243902   -96.585366 -102.500000    -98.926829   
Minnesota      -185.841463 -171.707317  -201.036585 -205.792683   -196.170732   
New Orleans     -63.182927  -63.

In [16]:
season_df = pd.read_csv("2017-18/17-18-cover.csv")
season_df.loc[13, "Team"] = "Oklahoma City"
season_df.loc[3, "Team"] = "L.A. Clippers"
season_df.loc[27, "Team"] = "L.A. Lakers"

In [17]:
season_df

Team  Cover %   Win  Loss  Tie
0       Milwaukee     61.3  57.0  36.0  4.0
1          Dallas     56.8  46.0  35.0  1.0
2      Sacramento     56.2  45.0  35.0  2.0
3   L.A. Clippers     55.2  48.0  39.0  1.0
4        Portland     54.2  52.0  44.0  2.0
5         Orlando     54.1  46.0  39.0  2.0
6            Utah     54.1  46.0  39.0  2.0
7     San Antonio     53.4  47.0  41.0  1.0
8           Miami     53.1  43.0  38.0  1.0
9        Brooklyn     52.9  46.0  41.0  0.0
10        Houston     52.2  47.0  43.0  3.0
11        Atlanta     51.2  42.0  40.0  0.0
12         Denver     51.0  49.0  47.0  0.0
13  Oklahoma City     50.6  44.0  43.0  0.0
14   Philadelphia     48.9  46.0  48.0  0.0
15        Detroit     48.8  41.0  43.0  2.0
16      Minnesota     48.8  40.0  42.0  0.0
17      Charlotte     48.8  39.0  41.0  2.0
18        Toronto     48.6  51.0  54.0  1.0
19         Boston     48.3  43.0  46.0  2.0
20        Memphis     48.1  39.0  42.0  1.0
21        Indiana     47.1  40.0  45.0  1.0
22    New Orleans     46.9  38.0  43.0  1.0
23      Cleveland     46.9  38.0  43.0  1.0
24     Washington     46.3  38.0  44.0  0.0
25        Phoenix     43.9  36.0  46.0  0.0
26        Chicago     43.8  35.0  45.0  2.0
27    L.A. Lakers     43.2  35.0  46.0  1.0
28   Golden State     43.1  44.0  58.0  2.0
29       New York     40.5  32.0  47.0  3.0

In [18]:
new_df = merged_df.merge(season_df, on='Team')

In [19]:
total_df = new_df.loc[:, ["Team", "Location", "Win", "Loss", "Tie","Cover %", "PercentBet_Spread", "Average_Line_Spread",
               "Average_Odds_Spread", "PTS", "FG_PCT", "FT_PCT", "FG3_PCT"]]

In [20]:
total_df.groupby('Team').mean().sort_values('PercentBet_Spread', ascending=False)

Win  Loss  Tie  Cover %  PercentBet_Spread  \
Team                                                         
Cleveland      38.0  43.0  1.0     46.9          56.035366   
Boston         43.0  46.0  2.0     48.3          55.576829   
Golden State   44.0  58.0  2.0     43.1          55.334146   
Portland       52.0  44.0  2.0     54.2          55.292683   
San Antonio    47.0  41.0  1.0     53.4          54.345122   
Oklahoma City  44.0  43.0  0.0     50.6          53.721951   
Houston        47.0  43.0  3.0     52.2          52.810976   
Toronto        51.0  54.0  1.0     48.6          52.335366   
Indiana        40.0  45.0  1.0     47.1          51.691463   
Philadelphia   46.0  48.0  0.0     48.9          51.246341   
Milwaukee      57.0  36.0  4.0     61.3          50.825610   
Washington     38.0  44.0  0.0     46.3          50.652439   
Denver         49.0  47.0  0.0     51.0          50.602439   
Utah           46.0  39.0  2.0     54.1          50.442683   
L.A. Lakers    35.0  46.0  1.0     43.2          50.186585   
Detroit        41.0  43.0  2.0     48.8          49.721951   
L.A. Clippers  48.0  39.0  1.0     55.2          49.298780   
Minnesota      40.0  42.0  0.0     48.8          48.875610   
New Orleans    38.0  43.0  1.0     46.9          48.634146   
New York       32.0  47.0  3.0     40.5          48.031707   
Charlotte      39.0  41.0  2.0     48.8          47.796341   
Phoenix        36.0  46.0  0.0     43.9          46.865854   
Dallas         46.0  35.0  1.0     56.8          46.793902   
Sacramento     45.0  35.0  2.0     56.2          46.562195   
Orlando        46.0  39.0  2.0     54.1          46.528049   
Brooklyn       46.0  41.0  0.0     52.9          46.425610   
Chicago        35.0  45.0  2.0     43.8          46.318293   
Miami          43.0  38.0  1.0     53.1          46.071951   
Memphis        39.0  42.0  1.0     48.1          45.642683   
Atlanta        42.0  40.0  0.0     51.2          45.332927   

               Average_Line_Spread  Average_Odds_Spread         PTS    FG_PCT  \
Team                                                                            
Cleveland                -4.414634          -107.873659  110.865854  0.477232   
Boston                   -2.640244          -107.499390  104.012195  0.451280   
Golden State             -8.502073          -107.717561  113.463415  0.503366   
Portland                 -1.543902          -107.983659  105.621951  0.453500   
San Antonio              -3.060976          -106.947073  102.731707  0.457756   
Oklahoma City            -4.465732          -107.900610  107.853659  0.453220   
Houston                  -7.490244          -107.662805  112.353659  0.460305   
Toronto                  -5.483537          -107.323293  111.658537  0.472683   
Indiana                   0.352439          -107.478171  105.560976  0.473073   
Philadelphia             -2.348537          -107.753659  109.804878  0.472463   
Milwaukee                -1.538415          -107.859268  106.475610  0.478927   
Washington               -2.140488          -107.598049  106.609756  0.467671   
Denver                   -1.896707          -107.729756  110.000000  0.470341   
Utah                     -1.539756          -108.101463  104.146341  0.462476   
L.A. Lakers               3.509634          -107.442927  108.073171  0.460890   
Detroit                   0.072317          -107.441463  103.768293  0.450159   
L.A. Clippers             0.446220          -107.796707  108.987805  0.472963   
Minnesota                -2.772439          -107.601463  109.512195  0.477512   
New Orleans              -0.912195          -107.882073  111.719512  0.484329   
New York                  4.510610          -107.743902  104.463415  0.464744   
Charlotte                -0.738902          -107.967195  108.219512  0.450598   
Phoenix                   7.356707          -107.408780  103.926829  0.443305   
Dallas                    4.140122          -107.648049  102.317073  0.445512   
Sacram

In [21]:
series_diff = (total_df.groupby('Team').mean()["Cover %"] - total_df.groupby('Team').mean()["PercentBet_Spread"])

In [22]:
grouped_df = total_df.groupby('Team').mean().sort_values('Cover %', ascending=False)

In [23]:
grouped_df=grouped_df.reset_index()

In [24]:
new_grouped_df = grouped_df.merge((series_diff.reset_index()), on="Team")

In [25]:
new_grouped_df.rename(columns={0: "Cover% - PercentBetSpread"}, inplace=True)

In [26]:
new_grouped_df

Team   Win  Loss  Tie  Cover %  PercentBet_Spread  \
0       Milwaukee  57.0  36.0  4.0     61.3          50.825610   
1          Dallas  46.0  35.0  1.0     56.8          46.793902   
2      Sacramento  45.0  35.0  2.0     56.2          46.562195   
3   L.A. Clippers  48.0  39.0  1.0     55.2          49.298780   
4        Portland  52.0  44.0  2.0     54.2          55.292683   
5            Utah  46.0  39.0  2.0     54.1          50.442683   
6         Orlando  46.0  39.0  2.0     54.1          46.528049   
7     San Antonio  47.0  41.0  1.0     53.4          54.345122   
8           Miami  43.0  38.0  1.0     53.1          46.071951   
9        Brooklyn  46.0  41.0  0.0     52.9          46.425610   
10        Houston  47.0  43.0  3.0     52.2          52.810976   
11        Atlanta  42.0  40.0  0.0     51.2          45.332927   
12         Denver  49.0  47.0  0.0     51.0          50.602439   
13  Oklahoma City  44.0  43.0  0.0     50.6          53.721951   
14   Philadelphia  46.0  48.0  0.0     48.9          51.246341   
15        Detroit  41.0  43.0  2.0     48.8          49.721951   
16      Charlotte  39.0  41.0  2.0     48.8          47.796341   
17      Minnesota  40.0  42.0  0.0     48.8          48.875610   
18        Toronto  51.0  54.0  1.0     48.6          52.335366   
19         Boston  43.0  46.0  2.0     48.3          55.576829   
20        Memphis  39.0  42.0  1.0     48.1          45.642683   
21        Indiana  40.0  45.0  1.0     47.1          51.691463   
22      Cleveland  38.0  43.0  1.0     46.9          56.035366   
23    New Orleans  38.0  43.0  1.0     46.9          48.634146   
24     Washington  38.0  44.0  0.0     46.3          50.652439   
25        Phoenix  36.0  46.0  0.0     43.9          46.865854   
26        Chicago  35.0  45.0  2.0     43.8          46.318293   
27    L.A. Lakers  35.0  46.0  1.0     43.2          50.186585   
28   Golden State  44.0  58.0  2.0     43.1          55.334146   
29       New York  32.0  47.0  3.0     40.5          48.031707   

    Average_Line_Spread  Average_Odds_Spread         PTS    FG_PCT    FT_PCT  \
0             -1.538415          -107.859268  106.475610  0.478927  0.784073   
1              4.140122          -107.648049  102.317073  0.445512  0.763183   
2              6.588537          -107.266707   98.829268  0.450768  0.740573   
3              0.446220          -107.796707  108.987805  0.472963  0.739317   
4             -1.543902          -107.983659  105.621951  0.453500  0.805256   
5             -1.539756          -108.101463  104.146341  0.462476  0.783317   
6              4.480122          -107.532561  103.402439  0.452963  0.761866   
7             -3.060976          -106.947073  102.731707  0.457756  0.778098   
8             -0.543537          -107.638171  103.414634  0.456024  0.755768   
9              4.537805          -107.556951  106.597561  0.442146  0.779146   
10            -7.490244          -107.662805  112.353659  0.460305  0.780232   
11             5.693293          -107.608171  103.353659  0.447720  0.787098   
12            -1.896707          -107.729756  110.000000  0.470341  0.770963   
13            -4.465732          -107.900610  107.853659  0.453220  0.714646   
14            -2.348537          -107.753659  109.804878  0.472463  0.759268   
15             0.072317          -107.441463  103.768293  0.450159  0.741378   
16            -0.738902          -107.967195  108.219512  0.450598  0.747366   
17            -2.772439          -107.601463  109.512195  0.477512  0.802329   
18            -5.483537          -107.323293  111.658537  0.472683  0.788061   
19            -2.640244          -107.499390  104.012195  0.451280  0.771622   
20             4.459756          -107.262195   99.329268  0.444256  0.782098   
21             0.352439          -107.478171  105.560976  0.473073  0.781451   
22            -4.414634          -107.873659  110.865854  0.477232  0.778085   
23            -0.912195          -107.882073  